version: '3'

services:
  web:
    build: ./web
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${CERTS_PATH}:/etc/nginx/certs:ro
    secrets:
      - ssl_certificate
      - ssl_certificate_key

secrets:
  ssl_certificate:
    file: ./private/ssl_certificate
  ssl_certificate_key:
    file: ./private/ssl_certificate_key
